#ifndef AURA_CONFIG_SBUS_H_INCLUDED
#define AURA_CONFIG_SBUS_H_INCLUDED


const int SBUS_CHANNELS = 16;
const uint8_t SBUS_FRAMELOST = (1 << 2);
const uint8_t SBUS_FAILSAFE = (1 << 3);



#endif // AURA_CONFIG_SBUS_H_INCLUDED
